### ISSUE TITLE
mod type 17 failed parse fix, scars pathfind error fix

### ISSUE THREAD

**Issue by TokcDK** [lmaydev/OpenConstructionSet#7]
OSC cant parse mod files of type 17
Mod for example: FF7 Tifa npc on Steam id: 2678023163. In my load order quite many of them.

There are some rough changes for type check and because the PR was made in develop branch.  There was added for type 17 reading of second integer in mod file as headr's size and change stream position to end of the header's data because I dont know which data are in bytes after masters and reference, before items data.

**Comment by TokcDK** [comment]
Sorry for double created issue and pr. Wrongly created issue before pr.

**Comment by lmaydev** [comment]
No problem mate. This has now been implemented.

https://github.com/lmaydev/OpenConstructionSet/pull/8#issuecomment-1104397022
