### ISSUE TITLE
How do I apply base gamedata patches in 3.0.1?

### ISSUE THREAD

**Issue by adwitkow** [lmaydev/OpenConstructionSet#9]
I've been using OCS 2.2.0 quite heavily to automate FCS datamining for the wiki. Recently I've decided that I would like to upgrade to 3.0.1 - however, I cannot get the base game files to patch over themselves to reflect the item states that FCS is showing.

What I mean is, as an example - in 3.0.1 the string id 923-gamedata.base, which is Guardless Katana, is named "Slim Katana" (very old name) after I build the base items.

For the record, here is how I'm currently building the items (although I also tried using the different `ModLoadTypes`, adding the gamedata files as basemods and overall, I played around with the `ModContextOptions` quite a lot to no avail).
```c#
var installations = await new InstallationService().DiscoverAllInstallationsAsync().ToDictionaryAsync(i => i.Identifier);
var installation = installations.Values.First();

var options = new ModContextOptions(
    Guid.NewGuid().ToString(),
    installation,
    loadGameFiles: ModLoadType.Base,
    loadEnabledMods: ModLoadType.Base,
    throwIfMissing: false);
    
var context = await new ContextBuilder().BuildAsync(options);
var contextItems = context.Items;
```

And, for comparison, here is how I used to do it in 2.2.0:
```c#
var installations = OcsDiscoveryService.Default.DiscoverAllInstallations();
var installation = installations.Values.First();

var options = new OcsDataContexOptions(
    Name: Guid.NewGuid().ToString(),
    Installation: installation,
    LoadGameFiles: ModLoadType.Base,
    LoadEnabledMods: ModLoadType.Base,
    ThrowIfMissing: false);
    
var contextItems = OcsDataContextBuilder.Default.Build(options).Items.Values.ToList();
```

**Comment by adwitkow** [comment]
And by the way, thank you for creating this. I've looked for a library like this back in 2020 and even had tried to create a reader for gamedata files myself back then, but I failed horribly :) Having OCS has been a godsend for filling the wiki and working with it is a pleasure. Cheers!

**Comment by lmaydev** [comment]
Aww thank you so much for your kind words. I appriciate it!

I haven't been able to work on the project for some time due to personal stuff going on.

I've found the source of the error and will look at getting a fix out soon.
